### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by ormf** [Islam0mar/cl-cxx-eigen#1]
The build of the lib for cl-cxx-eigen fails here:

[build]$ make
[ 33%] Generating ctags
ctags: invalid option -- 'e'
	Try 'ctags --help' for a complete list of options.
make[2]: *** [CMakeFiles/CTAGS.dir/build.make:71: CMakeFiles/CTAGS] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/CTAGS.dir/all] Fehler 2
make: *** [Makefile:91: all] Fehler 2
[build]$

**Comment by Islam0mar** [comment]
You could remove this custom target @ https://github.com/Islam0mar/cl-cxx-eigen/blob/master/CMakeLists.txt#L77.

**Comment by ormf** [comment]
ok, thanks! Wasn't sure the ctags weren't required.

**Comment by ormf** [comment]
The library compiles and loads fine (I checked all the steps with pathnames, etc. individually), but it doesn't seem to work:

CL-USER> (ql:quickload "cxx-eigen")
To load "cxx-eigen":
  Load 1 ASDF system:
    cxx-eigen
; Loading "cxx-eigen"
..............
("cxx-eigen")
CL-USER> (in-package :cxx-eigen)
#<PACKAGE "CXX-EIGEN">
CXX-EIGEN> (init)
T
CXX-EIGEN> (cxx-eigen::create-mat2 3 4)
; in: CREATE-MAT2 3
;     (CXX-EIGEN::CREATE-MAT2 3 4)
; 
; caught STYLE-WARNING:
;   undefined function: CXX-EIGEN::CREATE-MAT2
; 
; compilation unit finished
;   Undefined function:
;     CREATE-MAT2
;   caught 1 STYLE-WARNING condition
; Evaluation aborted on #<UNDEFINED-FUNCTION CREATE-MAT2 {1002BD0853}>.
CXX-EIGEN>

**Comment by Islam0mar** [comment]
You should call `(cxx-eigen:init)` to load shared library.

**Comment by Islam0mar** [comment]
Could you try `(cxx-eigen:init)` before `(in-package :cxx-eigen)`.
I am going to clean these things ISA.

**Comment by ormf** [comment]
Doesn't work here :-(

CL-USER> (ql:quickload "cxx-eigen")
To load "cxx-eigen":
  Load 1 ASDF system:
    cxx-eigen
; Loading "cxx-eigen"
..............
("cxx-eigen")
CL-USER> (cxx-eigen:init)
T
CL-USER> (in-package :cxx-eigen)
#<PACKAGE "CXX-EIGEN">
CXX-EIGEN> (init)
Caught error: Error registering module: eigen was already registered
T
CXX-EIGEN> (cxx-eigen::create-mat2 3 4)
; in: CREATE-MAT2 3
;     (CXX-EIGEN::CREATE-MAT2 3 4)
; 
; caught STYLE-WARNING:
;   undefined function: CXX-EIGEN::CREATE-MAT2
; 
; compilation unit finished
;   Undefined function:
;     CREATE-MAT2
;   caught 1 STYLE-WARNING condition

**Comment by ormf** [comment]
I can't find any definition of create-mat2 in any of the files. Am I missing something? The whole mechanism of instantiating (and accessing) classes in cl-cxx is quite obscure to me.

**Comment by Islam0mar** [comment]
Thanks for reporting.

I have updated `readme` @ https://github.com/Islam0mar/cl-cxx.

Kindly check the following:
- Check that https://github.com/Islam0mar/cl-cxx-eigen/blob/master/src/cxx-eigen.lisp#L5 is pointing to the correct shared libraries `libClCxx` and `libClCxx-Eigen`.
- To load class in lisp I used C++ to handle memory management, so class is allocated by C++ lib. and you have to call its costructor that you exposed `cxx-eigen:create-mat2`. 
- you don't need to `init` twice only once.
- It would help to see a list of the exported symbols from `cxx-eigen`.

**Comment by Islam0mar** [comment]
If not resolved kindly reopen.
